// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_s4_06wxpP7BSus5a9TkxvJEziLbvmn8',
    appId: '1:504195717910:web:311f248e3fab67d9318e37',
    messagingSenderId: '504195717910',
    projectId: 'nagaoka-lists',
    authDomain: 'nagaoka-lists.firebaseapp.com',
    storageBucket: 'nagaoka-lists.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuRWFQJ0dAjcX8Yabm4jr3ux9JBMim0Ho',
    appId: '1:504195717910:android:604178d14268d259318e37',
    messagingSenderId: '504195717910',
    projectId: 'nagaoka-lists',
    storageBucket: 'nagaoka-lists.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfzhinffS5BxWTRsUd4MYxN1B8vuS2uZM',
    appId: '1:504195717910:ios:abef40ac00723a78318e37',
    messagingSenderId: '504195717910',
    projectId: 'nagaoka-lists',
    storageBucket: 'nagaoka-lists.appspot.com',
    iosBundleId: 'com.example.nagaokaLists',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfzhinffS5BxWTRsUd4MYxN1B8vuS2uZM',
    appId: '1:504195717910:ios:abef40ac00723a78318e37',
    messagingSenderId: '504195717910',
    projectId: 'nagaoka-lists',
    storageBucket: 'nagaoka-lists.appspot.com',
    iosBundleId: 'com.example.nagaokaLists',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_s4_06wxpP7BSus5a9TkxvJEziLbvmn8',
    appId: '1:504195717910:web:ba7695e677a8c203318e37',
    messagingSenderId: '504195717910',
    projectId: 'nagaoka-lists',
    authDomain: 'nagaoka-lists.firebaseapp.com',
    storageBucket: 'nagaoka-lists.appspot.com',
  );

}